/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_http2client_Http2Client */

#ifndef _Included_com_http2client_Http2Client
#define _Included_com_http2client_Http2Client
#ifdef __cplusplus
extern "C" {
#endif
#undef com_http2client_Http2Client_BUFFER_SIZE
#define com_http2client_Http2Client_BUFFER_SIZE 1048576L
/*
 * Class:     com_http2client_Http2Client
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_http2client_Http2Client_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_http2client_Http2Client
 * Method:    nativeRequest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_http2client_Http2Client_nativeRequest
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_http2client_Http2Client
 * Method:    nativeCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_http2client_Http2Client_nativeCleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
