/*
 * Http2Client.c
 *
 * JNI bridge: connects Java Http2Client.java to the native C library.
 *
 * Implements the three JNI functions generated by `javac -h`:
 *   Java_Http2Client_nativeInit      -> calls initialiseEnv()
 *   Java_Http2Client_nativeRequest   -> calls handleRequest()
 *   Java_Http2Client_nativeCleanup   -> calls cleanupEnv()
 *
 * Mirrors nodejs/http2-addon.cc (N-API bridge) and the C API in Http2Client.h.
 */

#include "Http2Client_jni.h"  /* generated by javac -h (renamed to avoid clash) */

#include <string.h>

/* ── Forward declarations from the native C library (include/Http2Client.h) ──
 *
 * We forward-declare instead of #include "Http2Client.h" to avoid pulling
 * in the project's complex header dependencies (InetAddress.h, Basket.h, etc.).
 * The symbols are resolved at link time against libhttp2client.
 */
extern void initialiseEnv(void);
extern void cleanupEnv(void);
extern char* handleRequest(const char *requestJSONString, int *outLen);
extern void getBasketContent(char *basketStr, char *dest);

/* Buffer size must match Http2Client.java BUFFER_SIZE (1 MB) */
#define BRIDGE_BUFFER_SIZE (1024 * 1024)

/* Reuse a static buffer across calls (same as nodejs addon pattern) */
static char g_buffer[BRIDGE_BUFFER_SIZE];

/*
 * Class:     Http2Client
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Http2Client_nativeInit(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    initialiseEnv();
}

/*
 * Class:     Http2Client
 * Method:    nativeRequest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Http2Client_nativeRequest(JNIEnv *env, jclass cls, jstring requestJson) {
    (void)cls;

    const char *requestStr = (*env)->GetStringUTFChars(env, requestJson, NULL);
    if (requestStr == NULL) {
        return NULL; /* OutOfMemoryError already thrown by JVM */
    }

    int actualLen = 0;
    char *result = handleRequest(requestStr, &actualLen);

    (*env)->ReleaseStringUTFChars(env, requestJson, requestStr);

    if (result != NULL && actualLen > 0) {
        /* Ensure null-termination for NewStringUTF */
        if (actualLen >= BRIDGE_BUFFER_SIZE) {
            actualLen = BRIDGE_BUFFER_SIZE - 1;
        }
        getBasketContent(result, g_buffer);
        g_buffer[actualLen] = '\0';
        return (*env)->NewStringUTF(env, g_buffer);
    }

    return NULL;
}

/*
 * Class:     Http2Client
 * Method:    nativeCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Http2Client_nativeCleanup(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    cleanupEnv();
}
