/*
 * HttpClient.c
 *
 * JNI bridge: connects Java HttpClient.java to the native C library.
 *
 * Implements the three JNI functions generated by `javac -h`:
 *   Java_HttpClient_nativeInit      -> calls initialiseEnv()
 *   Java_HttpClient_nativeRequest   -> calls handleRequest()
 *   Java_HttpClient_nativeCleanup   -> calls cleanupEnv()
 *
 * Mirrors nodejs/http-addon.cc (N-API bridge) and the C API in HttpClient.h.
 */

#include "HttpClient_jni.h"  /* generated by javac -h (renamed to avoid clash) */

#include <string.h>
#include <stdlib.h>
#include <stdint.h>

/* ── Forward declarations from the native C library (include/HttpClient.h) ──
 *
 * We forward-declare instead of #include "HttpClient.h" to avoid pulling
 * in the project's complex header dependencies (InetAddress.h, Basket.h, etc.).
 * The symbols are resolved at link time against libhttpclient.
 */
extern void initialiseEnv(void);
extern void cleanupEnv(void);
extern intptr_t handleRequest(const char *requestJSONString);   /* returns basket pointer as intptr_t, 0 = failure */
extern char* setNonBlocking(const char *requestJSONString, int nonBlocking);
extern void freeJson(char *json);
extern void handleResponse(intptr_t basketHandle, char *dest, int capacity, int *outStatus, int *outLen);

/* Buffer size must match HttpClient.java BUFFER_SIZE (1 MB) */
#define BRIDGE_BUFFER_SIZE (1024 * 1024)

/*
 * Class:     HttpClient
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HttpClient_nativeInit(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    initialiseEnv();
}

/*
 * Class:     HttpClient
 * Method:    nativeRequest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HttpClient_nativeRequest(JNIEnv *env, jclass cls, jstring requestJson) {
    (void)cls;

    const char *requestStr = (*env)->GetStringUTFChars(env, requestJson, NULL);
    if (requestStr == NULL) {
        return NULL; /* OutOfMemoryError already thrown by JVM */
    }

    /* pin blocking mode: handleRequest picks the mode from "non-blocking" */
    char *blockingJson = setNonBlocking(requestStr, 0);
    (*env)->ReleaseStringUTFChars(env, requestJson, requestStr);
    if (blockingJson == NULL) {
        return NULL;
    }

    const intptr_t handle = handleRequest(blockingJson);
    freeJson(blockingJson);
    if (handle == 0) {
        return NULL;
    }

    /* Per-call heap buffer (NOT a shared static one): nativeRequest is
     * invoked concurrently from multiple Java threads, so a shared buffer
     * would race and return corrupted/interleaved responses. */
    int capacity = BRIDGE_BUFFER_SIZE;
    char *buffer = malloc(capacity);
    if (buffer == NULL) {
        return NULL; /* OOM: return null; caller treats it as a failed request */
    }

    int status = 0;
    int actualLen = 0;
    handleResponse(handle, buffer, capacity, &status, &actualLen);
    if (status == 2) {
        /* Response bigger than the bridge buffer: grow and re-collect. */
        char *bigger = realloc(buffer, (size_t) actualLen + 1);
        if (bigger == NULL) {
            free(buffer);
            return NULL;
        }
        buffer = bigger;
        capacity = actualLen + 1;
        handleResponse(handle, buffer, capacity, &status, &actualLen);
    }

    if (status != 1) {
        free(buffer);
        return NULL;
    }
    jstring out = (*env)->NewStringUTF(env, buffer);
    free(buffer);
    return out;
}

/*
 * Class:     HttpClient
 * Method:    nativeCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HttpClient_nativeCleanup(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    cleanupEnv();
}

/*
 * Class:     HttpClient
 * Method:    nativeStartRequest
 * Signature: (Ljava/lang/String;)J
 *
 * Non-blocking request: sends HEADERS/DATA and returns immediately with a
 * basket handle (0 = start failed). Mirrors handleRequest() on a request
 * carrying "non-blocking": 1 (forced here).
 */
JNIEXPORT jlong JNICALL Java_HttpClient_nativeStartRequest(JNIEnv *env, jclass cls, jstring requestJson) {
    (void)cls;

    const char *requestStr = (*env)->GetStringUTFChars(env, requestJson, NULL);
    if (requestStr == NULL) {
        return 0; /* OutOfMemoryError already thrown by JVM */
    }

    char *asyncJson = setNonBlocking(requestStr, 1);
    (*env)->ReleaseStringUTFChars(env, requestJson, requestStr);
    if (asyncJson == NULL) {
        return 0;
    }

    const intptr_t handle = handleRequest(asyncJson);
    freeJson(asyncJson);

    return (jlong) handle;
}

/*
 * Class:     HttpClient
 * Method:    nativePollRequest
 * Signature: (J)[Ljava/lang/Object;
 *
 * Poll a non-blocking request. Returns an Object[2]:
 *   [0] = Integer status (0 = in flight, 1 = completed, -1 = failed/timeout)
 *   [1] = String  response JSON (only when status != 0), or null
 */
JNIEXPORT jobjectArray JNICALL Java_HttpClient_nativePollRequest(JNIEnv *env, jclass cls, jlong basketHandle) {
    (void)cls;

    int capacity = BRIDGE_BUFFER_SIZE;
    char *buffer = malloc(capacity);
    if (buffer == NULL) {
        return NULL;
    }

    int status = 0;
    int outLen = 0;
    handleResponse((intptr_t) basketHandle, buffer, capacity, &status, &outLen);
    if (status == 2) {
        /* Response bigger than the bridge buffer: grow and re-collect. */
        char *bigger = realloc(buffer, (size_t) outLen + 1);
        if (bigger != NULL) {
            buffer = bigger;
            capacity = outLen + 1;
            handleResponse((intptr_t) basketHandle, buffer, capacity, &status, &outLen);
        }
    }

    /* Build Object[]{ Integer status, String data|null } */
    jclass objectClass = (*env)->FindClass(env, "java/lang/Object");
    if (objectClass == NULL) {
        free(buffer);
        return NULL;
    }
    jobjectArray arr = (*env)->NewObjectArray(env, 2, objectClass, NULL);
    if (arr == NULL) {
        free(buffer);
        return NULL;
    }

    jclass integerClass = (*env)->FindClass(env, "java/lang/Integer");
    if (integerClass != NULL) {
        jmethodID ctor = (*env)->GetMethodID(env, integerClass, "<init>", "(I)V");
        if (ctor != NULL) {
            jobject statusObj = (*env)->NewObject(env, integerClass, ctor, (jint) status);
            if (statusObj != NULL) {
                (*env)->SetObjectArrayElement(env, arr, 0, statusObj);
                (*env)->DeleteLocalRef(env, statusObj);
            }
        }
        (*env)->DeleteLocalRef(env, integerClass);
    }

    if (status != 0 && outLen > 0) {
        jstring dataStr = (*env)->NewStringUTF(env, buffer);
        if (dataStr != NULL) {
            (*env)->SetObjectArrayElement(env, arr, 1, dataStr);
            (*env)->DeleteLocalRef(env, dataStr);
        }
    }
    free(buffer);

    return arr;
}
