/*
 * Http2Client.c
 *
 * JNI bridge: connects Java Http2Client.java to the native C library.
 *
 * Implements the three JNI functions generated by `javac -h`:
 *   Java_Http2Client_nativeInit      -> calls initialiseEnv()
 *   Java_Http2Client_nativeRequest   -> calls handleRequest()
 *   Java_Http2Client_nativeCleanup   -> calls cleanupEnv()
 *
 * Mirrors nodejs/http2-addon.cc (N-API bridge) and the C API in Http2Client.h.
 */

#include "Http2Client_jni.h"  /* generated by javac -h (renamed to avoid clash) */

#include <string.h>
#include <stdlib.h>

/* ── Forward declarations from the native C library (include/Http2Client.h) ──
 *
 * We forward-declare instead of #include "Http2Client.h" to avoid pulling
 * in the project's complex header dependencies (InetAddress.h, Basket.h, etc.).
 * The symbols are resolved at link time against libhttp2client.
 */
extern void initialiseEnv(void);
extern void cleanupEnv(void);
extern char* handleRequest(const char *requestJSONString, int *outLen);
extern void getBasketContent(char *basketStr, char *dest);
extern long handleRequestAsync(const char *requestJSONString);
extern char* pollRequest(long requestId, int *outStatus, int *outLen);

/* Buffer size must match Http2Client.java BUFFER_SIZE (1 MB) */
#define BRIDGE_BUFFER_SIZE (1024 * 1024)

/*
 * Class:     Http2Client
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Http2Client_nativeInit(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    initialiseEnv();
}

/*
 * Class:     Http2Client
 * Method:    nativeRequest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Http2Client_nativeRequest(JNIEnv *env, jclass cls, jstring requestJson) {
    (void)cls;

    const char *requestStr = (*env)->GetStringUTFChars(env, requestJson, NULL);
    if (requestStr == NULL) {
        return NULL; /* OutOfMemoryError already thrown by JVM */
    }

    int actualLen = 0;
    char *result = handleRequest(requestStr, &actualLen);

    (*env)->ReleaseStringUTFChars(env, requestJson, requestStr);

    if (result != NULL && actualLen > 0) {
        if (actualLen >= BRIDGE_BUFFER_SIZE) {
            actualLen = BRIDGE_BUFFER_SIZE - 1;
        }
        /* Copy the basket into a per-call heap buffer (NOT a shared static one):
         * nativeRequest is invoked concurrently from multiple Java threads, so a
         * shared buffer would race and return corrupted/interleaved responses.
         * getBasketContent copies the content into the buffer and frees result. */
        char *buffer = malloc(actualLen + 1);
        if (buffer == NULL) {
            free(result);
            return NULL; /* OOM: return null; caller treats it as a failed request */
        }
        getBasketContent(result, buffer);
        buffer[actualLen] = '\0';
        jstring out = (*env)->NewStringUTF(env, buffer);
        free(buffer);
        return out;
    }

    return NULL;
}

/*
 * Class:     Http2Client
 * Method:    nativeCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Http2Client_nativeCleanup(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    cleanupEnv();
}

/*
 * Class:     Http2Client
 * Method:    nativeStartRequest
 * Signature: (Ljava/lang/String;)J
 *
 * Non-blocking request: sends HEADERS/DATA and returns immediately with a
 * request id (0 = start failed). Mirrors handleRequestAsync().
 */
JNIEXPORT jlong JNICALL Java_Http2Client_nativeStartRequest(JNIEnv *env, jclass cls, jstring requestJson) {
    (void)cls;

    const char *requestStr = (*env)->GetStringUTFChars(env, requestJson, NULL);
    if (requestStr == NULL) {
        return 0; /* OutOfMemoryError already thrown by JVM */
    }

    long id = handleRequestAsync(requestStr);
    (*env)->ReleaseStringUTFChars(env, requestJson, requestStr);

    return (jlong) id;
}

/*
 * Class:     Http2Client
 * Method:    nativePollRequest
 * Signature: (J)[Ljava/lang/Object;
 *
 * Poll a non-blocking request. Returns an Object[2]:
 *   [0] = Integer status (0 = in flight, 1 = completed, -1 = failed/timeout)
 *   [1] = String  response JSON (only when status != 0), or null
 */
JNIEXPORT jobjectArray JNICALL Java_Http2Client_nativePollRequest(JNIEnv *env, jclass cls, jlong requestId) {
    (void)cls;

    int status = 0;
    int outLen = 0;
    char *result = pollRequest((long) requestId, &status, &outLen);

    /* Build Object[]{ Integer status, String data|null } */
    jclass objectClass = (*env)->FindClass(env, "java/lang/Object");
    if (objectClass == NULL) {
        if (result != NULL) free(result);
        return NULL;
    }
    jobjectArray arr = (*env)->NewObjectArray(env, 2, objectClass, NULL);
    if (arr == NULL) {
        if (result != NULL) free(result);
        return NULL;
    }

    jclass integerClass = (*env)->FindClass(env, "java/lang/Integer");
    if (integerClass != NULL) {
        jmethodID ctor = (*env)->GetMethodID(env, integerClass, "<init>", "(I)V");
        if (ctor != NULL) {
            jobject statusObj = (*env)->NewObject(env, integerClass, ctor, (jint) status);
            if (statusObj != NULL) {
                (*env)->SetObjectArrayElement(env, arr, 0, statusObj);
                (*env)->DeleteLocalRef(env, statusObj);
            }
        }
        (*env)->DeleteLocalRef(env, integerClass);
    }

    if (result != NULL && outLen > 0) {
        if (outLen >= BRIDGE_BUFFER_SIZE) {
            outLen = BRIDGE_BUFFER_SIZE - 1;
        }
        char *buffer = malloc(outLen + 1);
        if (buffer != NULL) {
            getBasketContent(result, buffer); /* copies into buffer and frees result */
            buffer[outLen] = '\0';
            jstring dataStr = (*env)->NewStringUTF(env, buffer);
            free(buffer);
            if (dataStr != NULL) {
                (*env)->SetObjectArrayElement(env, arr, 1, dataStr);
                (*env)->DeleteLocalRef(env, dataStr);
            }
        } else {
            free(result);
        }
    }

    return arr;
}
