/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HttpClient */

#ifndef _Included_HttpClient
#define _Included_HttpClient
#ifdef __cplusplus
extern "C" {
#endif
#undef HttpClient_BUFFER_SIZE
#define HttpClient_BUFFER_SIZE 1048576L
/*
 * Class:     HttpClient
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HttpClient_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     HttpClient
 * Method:    nativeRequest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HttpClient_nativeRequest
  (JNIEnv *, jclass, jstring);

/*
 * Class:     HttpClient
 * Method:    nativeCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HttpClient_nativeCleanup
  (JNIEnv *, jclass);

/*
 * Class:     HttpClient
 * Method:    nativeStartRequest
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_HttpClient_nativeStartRequest
  (JNIEnv *, jclass, jstring);

/*
 * Class:     HttpClient
 * Method:    nativePollRequest
 * Signature: (J)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_HttpClient_nativePollRequest
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
