/*
 * HttpClient.c
 *
 * JNI bridge: connects Java HttpClient.java to the native C library.
 *
 * Implements the JNI functions generated by `javac -h`:
 *   Java_HttpClient_nativeInit                    -> calls initialiseEnv()
 *   Java_HttpClient_nativeRequest[Streaming]      -> calls handleRequest()
 *   Java_HttpClient_nativeStartRequest[Streaming] -> calls handleRequest()
 *   Java_HttpClient_nativePollRequest             -> calls handleResponse()
 *   Java_HttpClient_nativeCleanup                 -> calls cleanupEnv()
 *
 * The two *Streaming variants hand a ResponseListener to the library, which
 * then delivers the body chunk by chunk instead of collecting it.
 *
 * Mirrors nodejs/http-addon.cc (N-API bridge) and the C API in HttpClient.h.
 */

#include "HttpClient_jni.h"  /* generated by javac -h (renamed to avoid clash) */

#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <pthread.h>

/* Mirrors Error (include/Error.h), ResponseHeader (include/Basket.h) and
 * ResponseStream (include/ResponseStream.h). Declared here instead of included
 * so the bridge never pulls in the project's header chain; only the layout
 * matters and it has to match field for field. */
typedef struct {
    const char *code;
    const char *msg;
} HttpError;

typedef struct {
    char *name;
    char *value;
    int freeName;
    int freeValue;
} HttpHeader;

typedef struct {
    void (*onHeaders)(void *userData, const HttpHeader *headers, size_t numHeaders);
    int (*onData)(void *userData, const unsigned char *data, size_t len);
    void (*onComplete)(void *userData, HttpError error);
    void *userData;
} HttpStream;

/* ── Forward declarations from the native C library (include/HttpClient.h) ──
 *
 * We forward-declare instead of #include "HttpClient.h" to avoid pulling
 * in the project's complex header dependencies (InetAddress.h, Basket.h, etc.).
 * The symbols are resolved at link time against libhttpclient.
 */
extern void initialiseEnv(void);
extern void cleanupEnv(void);
extern intptr_t handleRequest(const char *requestJSONString, const HttpStream *stream);   /* returns basket pointer as intptr_t, 0 = failure; stream = ResponseStream contract, NULL lets the library collect the body itself */
extern char* setNonBlocking(const char *requestJSONString, int nonBlocking);
extern void freeJson(char *json);
extern void handleResponse(intptr_t basketHandle, char *dest, int capacity, int *outStatus, int *outLen);

/* Buffer size must match HttpClient.java BUFFER_SIZE (1 MB) */
#define BRIDGE_BUFFER_SIZE (1024 * 1024)

/* ── Streaming response (ResponseStream contract) ──
 *
 * The C core runs the contract on the thread that receives the bytes (the
 * connection reader), which the JVM has never seen, so every callback attaches
 * that thread first. No queueing is needed here, unlike the Node.js bridge: a
 * JNI call is synchronous, so onData hands the listener's verdict straight back
 * and `return true` stops the response at once.
 */
typedef struct {
    JavaVM *jvm;
    jobject listener;       /* global reference, alive for the whole exchange */
    jmethodID onHeaders;
    jmethodID onData;
    jmethodID onComplete;
} JniStreamContext;

/* A non-blocking streaming request outlives the call that started it, so its
 * context waits here until pollRequest reaps the id. */
typedef struct StreamContextEntry {
    jlong requestId;
    JniStreamContext *ctx;
    struct StreamContextEntry *next;
} StreamContextEntry;

static pthread_mutex_t streamContextLock = PTHREAD_MUTEX_INITIALIZER;
static StreamContextEntry *streamContexts = NULL;

static JNIEnv* attachCallbackThread(JniStreamContext *ctx, int *attachedHere);
static void detachCallbackThread(JniStreamContext *ctx, int attachedHere);
static void onStreamHeaders(void *userData, const HttpHeader *headers, size_t numHeaders);
static int onStreamData(void *userData, const unsigned char *data, size_t len);
static void onStreamComplete(void *userData, HttpError error);
static JniStreamContext* createStreamContext(JNIEnv *env, jobject listener);
static void freeStreamContext(JNIEnv *env, JniStreamContext *ctx);
static void registerStreamContext(jlong requestId, JniStreamContext *ctx);
static JniStreamContext* takeStreamContext(jlong requestId);
static void clearStreamContexts(JNIEnv *env);
static char* collectResponse(intptr_t handle, int *outStatus);
static HttpStream buildStreamContract(JniStreamContext *ctx);
static jstring runBlockingRequest(JNIEnv *env, jstring requestJson, JniStreamContext *ctx);
static jlong startAsyncRequest(JNIEnv *env, jstring requestJson, JniStreamContext *ctx);
static void clearListenerException(JNIEnv *env);
static void rejectListener(JNIEnv *env, const char *message);

static JNIEnv* attachCallbackThread(JniStreamContext *ctx, int *attachedHere) {
    JNIEnv *env = NULL;
    *attachedHere = 0;

    if ((*ctx->jvm)->GetEnv(ctx->jvm, (void **)&env, JNI_VERSION_1_6) == JNI_OK) {
        return env;
    }
    /* jni.h declares this C entry point as taking void** on every platform, so
     * the local JNIEnv* is always cast rather than passed through. */
    const jint attached = (*ctx->jvm)->AttachCurrentThread(ctx->jvm, (void **)&env, NULL);
    if (attached != JNI_OK) {
        return NULL;
    }

    *attachedHere = 1;
    return env;
}

static void detachCallbackThread(JniStreamContext *ctx, int attachedHere) {
    if (attachedHere) {
        (*ctx->jvm)->DetachCurrentThread(ctx->jvm);
    }
}

/* A listener that threw must not leave a pending exception on the reader thread,
 * where nothing would ever catch it. */
static void clearListenerException(JNIEnv *env) {
    if ((*env)->ExceptionCheck(env)) {
        (*env)->ExceptionDescribe(env);
        (*env)->ExceptionClear(env);
    }
}

/* The contract is all or nothing: rather than downgrading a half listener to a
 * buffered response, the request is refused and Java sees why. */
static void rejectListener(JNIEnv *env, const char *message) {
    jclass listenerError = (*env)->FindClass(env, "java/lang/IllegalArgumentException");
    if (listenerError == NULL) {
        return;
    }
    (*env)->ThrowNew(env, listenerError, message);
    (*env)->DeleteLocalRef(env, listenerError);
}

static void onStreamHeaders(void *userData, const HttpHeader *headers, size_t numHeaders) {
    JniStreamContext *ctx = (JniStreamContext *)userData;
    int attachedHere = 0;
    JNIEnv *env = attachCallbackThread(ctx, &attachedHere);
    if (env == NULL) {
        return;
    }

    /* LinkedHashMap keeps the wire order, ":status" first */
    jclass mapClass = (*env)->FindClass(env, "java/util/LinkedHashMap");
    jobject map = NULL;
    jmethodID put = NULL;
    if (mapClass != NULL) {
        jmethodID ctor = (*env)->GetMethodID(env, mapClass, "<init>", "()V");
        put = (*env)->GetMethodID(env, mapClass, "put",
                                 "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;");
        map = ctor != NULL ? (*env)->NewObject(env, mapClass, ctor) : NULL;
    }

    if (map != NULL && put != NULL) {
        for (size_t i = 0; i < numHeaders; i++) {
            if (headers[i].name == NULL) {
                continue;
            }
            jstring name = (*env)->NewStringUTF(env, headers[i].name);
            jstring value = (*env)->NewStringUTF(env,
                                                headers[i].value != NULL ? headers[i].value : "");
            if (name != NULL && value != NULL) {
                jobject previous = (*env)->CallObjectMethod(env, map, put, name, value);
                if (previous != NULL) {
                    (*env)->DeleteLocalRef(env, previous);
                }
            }
            if (name != NULL) {
                (*env)->DeleteLocalRef(env, name);
            }
            if (value != NULL) {
                (*env)->DeleteLocalRef(env, value);
            }
        }
        (*env)->CallVoidMethod(env, ctx->listener, ctx->onHeaders, map);
    }

    if (map != NULL) {
        (*env)->DeleteLocalRef(env, map);
    }
    if (mapClass != NULL) {
        (*env)->DeleteLocalRef(env, mapClass);
    }
    clearListenerException(env);
    detachCallbackThread(ctx, attachedHere);
}

static int onStreamData(void *userData, const unsigned char *data, size_t len) {
    JniStreamContext *ctx = (JniStreamContext *)userData;
    int attachedHere = 0;
    JNIEnv *env = attachCallbackThread(ctx, &attachedHere);
    if (env == NULL) {
        return 1;   /* the listener cannot be reached: stop instead of spinning */
    }

    /* the library reuses its decode buffer, so the chunk is copied for Java */
    int stop = 0;
    jbyteArray chunk = (*env)->NewByteArray(env, (jsize)len);
    if (chunk != NULL) {
        (*env)->SetByteArrayRegion(env, chunk, 0, (jsize)len, (const jbyte *)data);
        const jboolean verdict = (*env)->CallBooleanMethod(env, ctx->listener, ctx->onData, chunk);
        stop = verdict == JNI_TRUE ? 1 : 0;
        (*env)->DeleteLocalRef(env, chunk);
    }

    if ((*env)->ExceptionCheck(env)) {
        clearListenerException(env);
        stop = 1;
    }
    detachCallbackThread(ctx, attachedHere);
    return stop;
}

static void onStreamComplete(void *userData, HttpError error) {
    JniStreamContext *ctx = (JniStreamContext *)userData;
    int attachedHere = 0;
    JNIEnv *env = attachCallbackThread(ctx, &attachedHere);
    if (env == NULL) {
        return;
    }

    jstring code = error.code != NULL ? (*env)->NewStringUTF(env, error.code) : NULL;
    jstring message = error.msg != NULL ? (*env)->NewStringUTF(env, error.msg) : NULL;
    (*env)->CallVoidMethod(env, ctx->listener, ctx->onComplete, code, message);

    if (code != NULL) {
        (*env)->DeleteLocalRef(env, code);
    }
    if (message != NULL) {
        (*env)->DeleteLocalRef(env, message);
    }
    clearListenerException(env);
    detachCallbackThread(ctx, attachedHere);
}

/* NULL when no listener was passed, which keeps the library's own collector and
 * therefore a complete buffered response. */
static JniStreamContext* createStreamContext(JNIEnv *env, jobject listener) {
    if (listener == NULL) {
        return NULL;
    }

    jclass listenerClass = (*env)->GetObjectClass(env, listener);
    if (listenerClass == NULL) {
        return NULL;
    }

    JniStreamContext *ctx = (JniStreamContext *)calloc(1, sizeof(JniStreamContext));
    if (ctx != NULL) {
        ctx->onHeaders = (*env)->GetMethodID(env, listenerClass, "onHeaders", "(Ljava/util/Map;)V");
        ctx->onData = (*env)->GetMethodID(env, listenerClass, "onData", "([B)Z");
        ctx->onComplete = (*env)->GetMethodID(env, listenerClass, "onComplete",
                                             "(Ljava/lang/String;Ljava/lang/String;)V");
    }
    (*env)->DeleteLocalRef(env, listenerClass);

    if (ctx == NULL || ctx->onHeaders == NULL || ctx->onData == NULL || ctx->onComplete == NULL) {
        /* a missing method already left a NoSuchMethodError on this frame */
        (*env)->ExceptionClear(env);
        free(ctx);
        rejectListener(env, "listener must implement onHeaders, onData and onComplete");
        return NULL;
    }

    if ((*env)->GetJavaVM(env, &ctx->jvm) != JNI_OK) {
        free(ctx);
        rejectListener(env, "cannot reach the JVM from the response callbacks");
        return NULL;
    }
    /* the exchange outlives this frame and runs on another thread */
    ctx->listener = (*env)->NewGlobalRef(env, listener);
    if (ctx->listener == NULL) {
        free(ctx);
        rejectListener(env, "cannot keep the listener alive for the response");
        return NULL;
    }
    return ctx;
}

static void freeStreamContext(JNIEnv *env, JniStreamContext *ctx) {
    if (ctx == NULL) {
        return;
    }
    if (ctx->listener != NULL && env != NULL) {
        (*env)->DeleteGlobalRef(env, ctx->listener);
    }
    free(ctx);
}

static void registerStreamContext(jlong requestId, JniStreamContext *ctx) {
    StreamContextEntry *entry = (StreamContextEntry *)calloc(1, sizeof(StreamContextEntry));
    if (entry == NULL) {
        /* the library already holds the context, so leaking it is the safe side:
         * freeing it here would leave the callbacks with a dangling userData */
        return;
    }

    entry->requestId = requestId;
    entry->ctx = ctx;

    pthread_mutex_lock(&streamContextLock);
    entry->next = streamContexts;
    streamContexts = entry;
    pthread_mutex_unlock(&streamContextLock);
}

static JniStreamContext* takeStreamContext(jlong requestId) {
    pthread_mutex_lock(&streamContextLock);
    StreamContextEntry **slot = &streamContexts;
    while (*slot != NULL) {
        if ((*slot)->requestId == requestId) {
            StreamContextEntry *found = *slot;
            *slot = found->next;
            pthread_mutex_unlock(&streamContextLock);

            JniStreamContext *ctx = found->ctx;
            free(found);
            return ctx;
        }
        slot = &(*slot)->next;
    }
    pthread_mutex_unlock(&streamContextLock);
    return NULL;
}

/* Drops every context still waiting for a poll, which is what a non-blocking
 * streaming request nobody reaped leaves behind. */
static void clearStreamContexts(JNIEnv *env) {
    pthread_mutex_lock(&streamContextLock);
    StreamContextEntry *entry = streamContexts;
    streamContexts = NULL;
    pthread_mutex_unlock(&streamContextLock);

    while (entry != NULL) {
        StreamContextEntry *next = entry->next;
        freeStreamContext(env, entry->ctx);
        free(entry);
        entry = next;
    }
}

/* Copies the response JSON out of `handle` into a fresh buffer, growing it when
 * the library reports the first attempt was truncated (status 2). NULL when
 * there is nothing to hand back; *outStatus always carries the probe result. */
static char* collectResponse(intptr_t handle, int *outStatus) {
    int capacity = BRIDGE_BUFFER_SIZE;
    char *buffer = (char *)malloc(capacity);
    if (buffer == NULL) {
        /* reported as "still in flight": a non-blocking request stays registered
         * and the next poll tries again, instead of being reaped with no result */
        *outStatus = 0;
        return NULL;
    }

    int status = 0;
    int outLen = 0;
    handleResponse(handle, buffer, capacity, &status, &outLen);
    if (status == 2) {
        /* response bigger than the bridge buffer: grow and re-collect */
        char *bigger = (char *)realloc(buffer, (size_t) outLen + 1);
        if (bigger == NULL) {
            free(buffer);
            *outStatus = 0;
            return NULL;
        }
        buffer = bigger;
        capacity = outLen + 1;
        handleResponse(handle, buffer, capacity, &status, &outLen);
    }

    *outStatus = status;
    /* a failed non-blocking request (-1) still carries its error JSON */
    if (status == 0 || outLen <= 0) {
        free(buffer);
        return NULL;
    }
    return buffer;
}

/* Fills the contract the library copies into its sink. userData points back at
 * the context, which is how the callbacks find the listener. */
static HttpStream buildStreamContract(JniStreamContext *ctx) {
    HttpStream contract;
    memset(&contract, 0, sizeof(contract));
    if (ctx != NULL) {
        contract.onHeaders = onStreamHeaders;
        contract.onData = onStreamData;
        contract.onComplete = onStreamComplete;
        contract.userData = ctx;
    }
    return contract;
}

/* Blocking exchange shared by nativeRequest and nativeRequestStreaming: a NULL
 * context passes no contract, so the library collects the body itself. Takes
 * ownership of ctx either way. */
static jstring runBlockingRequest(JNIEnv *env, jstring requestJson, JniStreamContext *ctx) {
    const char *requestStr = (*env)->GetStringUTFChars(env, requestJson, NULL);
    if (requestStr == NULL) {
        freeStreamContext(env, ctx);
        return NULL; /* OutOfMemoryError already thrown by JVM */
    }

    /* pin blocking mode: handleRequest picks the mode from "non-blocking" */
    char *blockingJson = setNonBlocking(requestStr, 0);
    (*env)->ReleaseStringUTFChars(env, requestJson, requestStr);
    if (blockingJson == NULL) {
        freeStreamContext(env, ctx);
        return NULL;
    }

    HttpStream contract = buildStreamContract(ctx);
    const intptr_t handle = handleRequest(blockingJson, ctx != NULL ? &contract : NULL);
    freeJson(blockingJson);

    int status = 0;
    char *json = NULL;
    if (handle != 0) {
        json = collectResponse(handle, &status);
    }
    /* the basket is gone by now, so no callback can reach the listener again */
    freeStreamContext(env, ctx);

    if (json == NULL) {
        return NULL;
    }
    jstring out = (*env)->NewStringUTF(env, json);
    free(json);
    return out;
}

/* Non-blocking exchange shared by nativeStartRequest and
 * nativeStartRequestStreaming: sends HEADERS/DATA and returns immediately with
 * a basket handle (0 = start failed). Takes ownership of ctx either way. */
static jlong startAsyncRequest(JNIEnv *env, jstring requestJson, JniStreamContext *ctx) {
    const char *requestStr = (*env)->GetStringUTFChars(env, requestJson, NULL);
    if (requestStr == NULL) {
        freeStreamContext(env, ctx);
        return 0; /* OutOfMemoryError already thrown by JVM */
    }

    char *asyncJson = setNonBlocking(requestStr, 1);
    (*env)->ReleaseStringUTFChars(env, requestJson, requestStr);
    if (asyncJson == NULL) {
        freeStreamContext(env, ctx);
        return 0;
    }

    HttpStream contract = buildStreamContract(ctx);
    const intptr_t handle = handleRequest(asyncJson, ctx != NULL ? &contract : NULL);
    freeJson(asyncJson);

    if (handle == 0) {
        freeStreamContext(env, ctx);
        return 0;
    }
    if (ctx != NULL) {
        /* the reader thread keeps calling the listener until pollRequest reaps it */
        registerStreamContext((jlong) handle, ctx);
    }
    return (jlong) handle;
}

/*
 * Class:     HttpClient
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HttpClient_nativeInit(JNIEnv *env, jclass cls) {
    (void)env;
    (void)cls;
    initialiseEnv();
}

/*
 * Class:     HttpClient
 * Method:    nativeRequest
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HttpClient_nativeRequest(JNIEnv *env, jclass cls, jstring requestJson) {
    (void)cls;
    return runBlockingRequest(env, requestJson, NULL);
}

/*
 * Class:     HttpClient
 * Method:    nativeRequestStreaming
 * Signature: (Ljava/lang/String;LHttpClient$ResponseListener;)Ljava/lang/String;
 *
 * Blocking request whose body is delivered to the listener chunk by chunk. The
 * listener runs on the connection reader thread, so it is released only once
 * the exchange is over.
 */
JNIEXPORT jstring JNICALL Java_HttpClient_nativeRequestStreaming(JNIEnv *env, jclass cls, jstring requestJson,
                                                               jobject listener) {
    (void)cls;
    JniStreamContext *ctx = createStreamContext(env, listener);
    if (ctx == NULL) {
        /* the listener was refused: the pending exception is the caller's answer */
        return NULL;
    }
    return runBlockingRequest(env, requestJson, ctx);
}

/*
 * Class:     HttpClient
 * Method:    nativeCleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HttpClient_nativeCleanup(JNIEnv *env, jclass cls) {
    (void)cls;
    /* reaps the in-flight requests, so no listener can be called afterwards */
    cleanupEnv();
    clearStreamContexts(env);
}

/*
 * Class:     HttpClient
 * Method:    nativeStartRequest
 * Signature: (Ljava/lang/String;)J
 *
 * Non-blocking request: sends HEADERS/DATA and returns immediately with a
 * basket handle (0 = start failed). Mirrors handleRequest() on a request
 * carrying "non-blocking": 1 (forced here).
 */
JNIEXPORT jlong JNICALL Java_HttpClient_nativeStartRequest(JNIEnv *env, jclass cls, jstring requestJson) {
    (void)cls;
    return startAsyncRequest(env, requestJson, NULL);
}

/*
 * Class:     HttpClient
 * Method:    nativeStartRequestStreaming
 * Signature: (Ljava/lang/String;LHttpClient$ResponseListener;)J
 *
 * Non-blocking streaming request: the listener stays registered against the
 * returned id, because the reader thread keeps calling it until pollRequest
 * reaps that id.
 */
JNIEXPORT jlong JNICALL Java_HttpClient_nativeStartRequestStreaming(JNIEnv *env, jclass cls, jstring requestJson,
                                                                 jobject listener) {
    (void)cls;
    JniStreamContext *ctx = createStreamContext(env, listener);
    if (ctx == NULL) {
        /* the listener was refused: the pending exception is the caller's answer */
        return 0;
    }
    return startAsyncRequest(env, requestJson, ctx);
}

/*
 * Class:     HttpClient
 * Method:    nativePollRequest
 * Signature: (J)[Ljava/lang/Object;
 *
 * Poll a non-blocking request. Returns an Object[2]:
 *   [0] = Integer status (0 = in flight, 1 = completed, -1 = failed/timeout)
 *   [1] = String  response JSON (only when status != 0), or null
 */
JNIEXPORT jobjectArray JNICALL Java_HttpClient_nativePollRequest(JNIEnv *env, jclass cls, jlong basketHandle) {
    (void)cls;

    int status = 0;
    char *json = collectResponse((intptr_t) basketHandle, &status);

    /* The exchange ends with the final result (1 = done, -1 = failed); only then
     * may the listener go, since the reader thread calls it right up to here. */
    if (status == 1 || status == -1) {
        freeStreamContext(env, takeStreamContext(basketHandle));
    }

    /* Build Object[]{ Integer status, String data|null } */
    jclass objectClass = (*env)->FindClass(env, "java/lang/Object");
    if (objectClass == NULL) {
        free(json);
        return NULL;
    }
    jobjectArray arr = (*env)->NewObjectArray(env, 2, objectClass, NULL);
    if (arr == NULL) {
        free(json);
        return NULL;
    }

    jclass integerClass = (*env)->FindClass(env, "java/lang/Integer");
    if (integerClass != NULL) {
        jmethodID ctor = (*env)->GetMethodID(env, integerClass, "<init>", "(I)V");
        if (ctor != NULL) {
            jobject statusObj = (*env)->NewObject(env, integerClass, ctor, (jint) status);
            if (statusObj != NULL) {
                (*env)->SetObjectArrayElement(env, arr, 0, statusObj);
                (*env)->DeleteLocalRef(env, statusObj);
            }
        }
        (*env)->DeleteLocalRef(env, integerClass);
    }

    if (json != NULL) {
        jstring dataStr = (*env)->NewStringUTF(env, json);
        if (dataStr != NULL) {
            (*env)->SetObjectArrayElement(env, arr, 1, dataStr);
            (*env)->DeleteLocalRef(env, dataStr);
        }
    }
    free(json);

    return arr;
}
