//
// Created by Intuition on 25-7-11.
//

#ifndef ERROR_H
#define ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
	NO = -1,
	OK = 0,
	ERROR_INVALID_PARAM,
	ERROR_SOCKET_CREATE,
	ERROR_HOST_RESOLVE,
	ERROR_CONNECT,
	ERROR_SSL_CTX_CREATE,
	ERROR_SSL_HANDSHAKE,
	ERROR_ALPN,
	ERROR_SESSION_MAGIC_NOT_MATCHED,
	ERROR_SESSION_IS_INACTIVE,
	ERROR_URL_PARSE,
	ERROR_SEND_MAGIC,
	ERROR_SEND_REQUEST,
	ERROR_RECEIVE_RESPONSE,
	ERROR_TIMEOUT,
	ERROR_UNKNOWN
} ErrorType;

typedef struct {
	const char *code;
	const char *msg;
} Error;

extern const Error ERR_NONE;

extern const Error ERR_SYSTEM_MEMORY_ALLOCATION_FAILED;
extern const Error ERR_SYSTEM_SHARED_MEMORY_NOT_EXIT;
extern const Error ERR_SYSTEM_SHARED_MEMORY_MMAP_FAILED;

extern const Error ERR_SESSION_SSL_CONNECT_FAILED;
extern const Error ERR_SESSION_SSL_ALPN_NEGOTIATION_FAILED;
extern const Error ERR_SESSION_MAGIC_INCORRECT;
extern const Error ERR_SESSION_INACTIVE;
extern const Error ERR_SESSION_HOST_RESOLVE_FAILED;
extern const Error ERR_SESSION_SOCKET_CREATION_FAILED;
extern const Error ERR_SESSION_SOCKET_NONBLOCK_SETTING_FAILED;
extern const Error ERR_SESSION_SOCKET_CONNECTING_FAILED;
extern const Error ERR_SESSION_SOCKET_INVALID_FILE_DESCRIPTOR;
extern const Error ERR_SESSION_SOCKET_CONNECTING_TIMEOUT;
extern const Error ERR_SESSION_SOCKET_NO_AVAILABLE_ADDRESS;
extern const Error ERR_SESSION_SOCKET_CONNECTING_UNKNOWN_ERROR;
extern const Error ERR_SESSION_SSL_CTX_CREATION_FAILED;
extern const Error ERR_SESSION_SSL_OBJECT_CREATION_FAILED;
extern const Error ERR_SESSION_SSL_FAILED_TO_ASSOCIATE_SOCKET;
extern const Error ERR_SESSION_FAILED_TO_CONNECT_TO_SHARED_MEMORY_POOL;
extern const Error ERR_SESSION_SOCKET_CONNECTING_REFUSED;
extern const Error ERR_SESSION_SETTINGS_TIMEOUT;
extern const Error ERR_SESSION_GO_AWAY;

extern const Error ERR_REQUEST_PARSING_STRING_TO_JSON_FAILED;
extern const Error ERR_REQUEST_MISSING_HEADERS;
extern const Error ERR_REQUEST_PARSING_URL_FAILED;
extern const Error ERR_REQUEST_PARSING_METHOD_FAILED;
extern const Error ERR_REQUEST_PARSING_USERAGENT_FAILED;
extern const Error ERR_REQUEST_PARSING_CONTENTLENGTH_FAILED;
extern const Error ERR_REQUEST_INCORRECT_CONTENTLENGTH_TYPE;
extern const Error ERR_REQUEST_UNSUPPORTED_METHOD;
extern const Error ERR_REQUEST_UNSUPPORTED_USERAGENT;
extern const Error ERR_REQUEST_SENDING_HTTP2_HEADERS_FRAME_FAILED;
extern const Error ERR_REQUEST_SENDING_HTTP2_DATA_FRAME_FAILED;
extern const Error ERR_REQUEST_SENDING_HTTP2_PREFACE_FRAME_FAILED;
extern const Error ERR_REQUEST_SENDING_HTTP2_SETTINGS_FRAME_FAILED;
extern const Error ERR_REQUEST_SENDING_HTTP2_WINDOW_UPDATE_FRAME_FAILED;
extern const Error ERR_REQUEST_UNKNOWN_PSEUDO_HEADER;

extern const Error ERR_RESPONSE_READING_CONNECTION_ERROR;
extern const Error ERR_RESPONSE_READING_UNKNOWN_ERROR;
extern const Error ERR_RESPONSE_NO_CONTENT_AFTER_READING_TIMEOUT;
extern const Error ERR_RESPONSE_PARTIAL_CONTENT_AFTER_READING_TIMEOUT;
extern const Error ERR_RESPONSE_DECODING_HEADERS_FRAME_FAILED;
extern const Error ERR_RESPONSE_DECODING_GOAWAY_FRAME_FAILED;
extern const Error ERR_RESPONSE_GZIP_INFLATE_FAILED;
extern const Error ERR_RESPONSE_BROTLI_INFLATE_FAILED;
extern const Error ERR_RESPONSE_DEFLATE_INFLATE_FAILED;
extern const Error ERR_RESPONSE_ZSTD_INFLATE_FAILED;
extern const Error ERR_RESPONSE_INFLATE_UNKNOWN_ERROR;
extern const Error ERR_RESPONSE_RST_STREAM_ERROR;

extern const Error ERR_PROXY_HOST_RESOLVE_FAILED;
extern const Error ERR_PROXY_SOCKET_CREATION_FAILED;
extern const Error ERR_PROXY_SOCKET_NONBLOCK_SETTING_FAILED;
extern const Error ERR_PROXY_SOCKET_CONNECTING_FAILED;
extern const Error ERR_PROXY_SOCKET_INVALID_FILE_DESCRIPTOR;
extern const Error ERR_PROXY_SOCKET_CONNECTING_TIMEOUT;
extern const Error ERR_PROXY_SOCKET_CONNECTING_UNKNOWN_ERROR;
extern const Error ERR_PROXY_SEND_CONNECT_REQUEST_FAILED;
extern const Error ERR_PROXY_AUTHORIZATION_FAILED;
extern const Error ERR_PROXY_UNEXPECTED_RESPONSE;
extern const Error ERR_PROXY_SOCKET_CONNECTING_REFUSED;


#ifdef __cplusplus
}
#endif

#endif //ERROR_H
